name: Raise Issue on CI Failure

on:
  workflow_run:
    workflows: ["Python CI with Logging"]
    types:
      - completed

jobs:
  create-issue-if-failed:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
    - name: Create Issue
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issueTitle = "🔴 CI Failed: Python CI with Logging";
          const issueBody = `
The CI workflow **Python CI with Logging** failed.

🔗 [View failed run logs](${{ github.event.workflow_run.html_url }})

Please investigate and fix the issue.
          `;

          const { data: issues } = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
          });

          const issueExists = issues.some(issue =>
            issue.title === issueTitle
          );

          if (!issueExists) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['ci-failure']
            });
          } else {
            console.log("An issue already exists for this CI failure.");
          }
